name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main, dev]
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Pull Docker image
      run: docker pull solardust8/mlops_study_1:latest

    - name: Run Docker container without server
      run: docker run -d --name mlops_study_1 solardust8/mlops_study_1:latest tail -f /dev/null

    - name: Execute unit test inside container
      run: docker exec mlops_study_1 python3 src/unit_tests/unit_test_train.py

    - name: Execute func test inside container
      run: docker exec mlops_study_1 python3 src/predict.py --mode infere --tests func

    - name: Stop and remove Docker container
      if: always()
      run: |
        docker stop mlops_study_1
        docker rm mlops_study_1
