name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download weights SpamHam
      uses: k0staa/download-gdrive-file-action@v1
      with:
        service-account-key-json: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
        download-file-name: SpamHam_weights/SpamHam/model.safetensors
        download-to: ./weights/SpamHamModel/

    - name: Download weights Distilbert
      uses: k0staa/download-gdrive-file-action@v1
      with:
        service-account-key-json: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
        download-file-name: SpamHam_weights/Distilbert/model.safetensors
        download-to: ./weights/DistilBert_4seqSls_base_cased/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: solardust8/mlops_study_1:latest
        no-cache: true
